// ==========================================================================
// Memory Photos Data Configuration
// Easily replace images, captions, categories, dates, and sticky notes
// ==========================================================================

export const MEMORIES_DATA = [
  {
    id: 1,
    image: '/kosmo.png',
    fallbackBg: 'linear-gradient(135deg, #1e3a8a, #0b1938)',
    caption: 'Cold Milo at Kosmo Café — where it all began ☕',
    date: 'The Beginning',
    category: 'Favorites',
    tilt: '-2.5deg',
    size: 'medium', // 'small' | 'medium' | 'large'
    stickyNote: 'first outing 💙',
    stickyPosition: 'top-right',
  },
  {
    id: 2,
    image: '/first selfie.jpeg',
    fallbackBg: 'linear-gradient(135deg, #2563eb, #172554)',
    caption: 'Our first selfie together 📸',
    date: 'First Selfie',
    category: 'Favorites',
    tilt: '3deg',
    size: 'large',
    stickyNote: 'day one vibes ✨',
    stickyPosition: 'bottom-left',
  },
  {
    id: 3,
    image: '/first snap of us.jpeg',
    fallbackBg: 'linear-gradient(135deg, #1d4ed8, #0f172a)',
    caption: 'First snap of us and all the mischievous energy 😂',
    date: 'Pure Mischief',
    category: 'Funny',
    tilt: '-4deg',
    size: 'medium',
    stickyNote: 'troublemakers 😂',
    stickyPosition: 'top-left',
  },
  {
    id: 4,
    image: '/both like.jpeg',
    fallbackBg: 'linear-gradient(135deg, #3b82f6, #1e293b)',
    caption: 'A picture that both of us truly love 💙',
    date: 'Shared Favorite',
    category: 'Favorites',
    tilt: '2deg',
    size: 'small',
    stickyNote: 'both love this ✨',
    stickyPosition: 'top-right',
  },
  {
    id: 5,
    image: '/favofmine.jpeg',
    fallbackBg: 'linear-gradient(135deg, #1e40af, #09173b)',
    caption: 'Definitely one of my absolute favorites ✨',
    date: 'Special',
    category: 'Favorites',
    tilt: '-3.5deg',
    size: 'large',
    stickyNote: 'so special 💙',
    stickyPosition: 'bottom-right',
  },
  {
    id: 6,
    image: '/all time fav.jpeg',
    fallbackBg: 'linear-gradient(135deg, #1d4ed8, #030712)',
    caption: 'All-time favorite candid moment & genuine smile.',
    date: 'All Time Fav',
    category: 'Favorites',
    tilt: '2.5deg',
    size: 'medium',
    stickyNote: 'candid smile 💫',
    stickyPosition: 'top-right',
  },
  {
    id: 7,
    image: '/chat went craze.jpeg',
    fallbackBg: 'linear-gradient(135deg, #2563eb, #0b1938)',
    caption: 'Late night chats, craziness & endless laughs 🤪',
    date: 'Crazy Chats',
    category: 'Funny',
    tilt: '-2deg',
    size: 'small',
    stickyNote: 'pure chaos 🤪',
    stickyPosition: 'top-left',
  },
  {
    id: 8,
    image: '/random but become favourite.jpeg',
    fallbackBg: 'linear-gradient(135deg, #3b82f6, #172554)',
    caption: 'Random candid moment that turned into a favorite 💫',
    date: 'Unplanned Magic',
    category: 'Random',
    tilt: '3.5deg',
    size: 'medium',
    stickyNote: 'unexpected fav ✨',
    stickyPosition: 'bottom-right',
  },
  {
    id: 9,
    image: '/earlymorningride.jpeg',
    fallbackBg: 'linear-gradient(135deg, #1e3a8a, #0b1938)',
    caption: 'Early morning ride on the open highway 🛣️',
    date: 'Highway Sunrise',
    category: 'Trip',
    tilt: '-2deg',
    size: 'medium',
    stickyNote: 'highway ride 🌅',
    stickyPosition: 'top-right',
  },
  {
    id: 10,
    image: '/golconda in rain.jpeg',
    fallbackBg: 'linear-gradient(135deg, #1d4ed8, #1e293b)',
    caption: 'Golconda Fort in the rain — misty and beautiful 🌧️',
    date: 'Rainy Adventure',
    category: 'Trip',
    tilt: '3deg',
    size: 'small',
    stickyNote: 'rain & fort 🏰',
    stickyPosition: 'bottom-left',
  },
  {
    id: 11,
    image: '/hyd trip starts.jpeg',
    fallbackBg: 'linear-gradient(135deg, #2563eb, #0f172a)',
    caption: 'From Kosmo Café all the way to Hyderabad 🚗',
    date: 'The Road Trip',
    category: 'Trip',
    tilt: '-3deg',
    size: 'large',
    stickyNote: 'trip begins 🚗',
    stickyPosition: 'top-right',
  },
];

export const FEATURED_SPECIAL_MEMORY = {
  id: 999,
  image: '/chowmalla fav pic.jpeg',
  fallbackBg: 'linear-gradient(135deg, #1d4ed8, #060e24)',
  title: 'THE ONE I KEEP COMING BACK TO',
  lead: 'Some pictures are just pictures.',
  punchline: 'And some somehow become memories.',
  tag: 'Chowmahalla Palace 💙',
};

export const SPECIAL_VIDEO_MEMORY = {
  src: '/our video.mp4',
  title: 'A MOMENT IN MOTION',
  subtitle: 'Some memories are too special to stay frozen in pictures.',
  caption: 'Laughs, craziness, and little moments caught on camera 🎬💙',
  tag: 'Special Video 🎥',
};

export const FILM_STRIP_PHOTOS = [
  { id: 'f1', src: '/earlymorningride.jpeg', label: 'Highway Ride', bg: '#1e3a8a' },
  { id: 'f2', src: '/golconda in rain.jpeg', label: 'Rainy Fort', bg: '#2563eb' },
  { id: 'f3', src: '/kosmo.png', label: 'Kosmo Café', bg: '#1d4ed8' },
  { id: 'f4', src: '/both like.jpeg', label: 'Our Favorite', bg: '#1e40af' },
  { id: 'f5', src: '/all time fav.jpeg', label: 'Candid Smile', bg: '#3b82f6' },
  { id: 'f6', src: '/hyd trip starts.jpeg', label: 'Trip Begins', bg: '#172554' },
];

export const CATEGORIES = [
  { id: 'All', label: 'All' },
  { id: 'Favorites', label: 'Favorites ❤️' },
  { id: 'Funny', label: 'Funny 😂' },
  { id: 'Random', label: 'Random ✨' },
  { id: 'Trip', label: 'Trip 🚗' },
];
