// ==========================================================================
// Friendship Words Data Configuration
// Easily configurable words, descriptions, sizes, and status report data
// ==========================================================================

export const FLOATING_WORDS = [
  {
    id: 'unexpected',
    word: 'Unexpected',
    description: "You weren't exactly part of the plan... but somehow you became part of the story.",
    size: 'lg', // 'sm' | 'md' | 'lg' | 'xl'
    color: '#93C5FD',
    glowColor: 'rgba(147, 197, 253, 0.45)',
    defaultPos: { x: -35, y: -25 },
    delay: 0.1,
  },
  {
    id: 'random',
    word: 'Random',
    description: 'Some of our best conversations probably started with absolutely nothing.',
    size: 'md',
    color: '#BAE6FD',
    glowColor: 'rgba(186, 230, 253, 0.4)',
    defaultPos: { x: 28, y: -32 },
    delay: 0.2,
  },
  {
    id: 'comfortable',
    word: 'Comfortable',
    description: 'Somehow, talking to you became surprisingly and effortlessly easy.',
    size: 'lg',
    color: '#FFFFFF',
    glowColor: 'rgba(255, 255, 255, 0.4)',
    defaultPos: { x: -18, y: -5 },
    delay: 0.3,
  },
  {
    id: 'chaotic',
    word: 'Chaotic',
    description: 'Because apparently normal, calm conversations were never an option. 😂',
    size: 'xl',
    color: '#60A5FA',
    glowColor: 'rgba(96, 165, 250, 0.55)',
    defaultPos: { x: 34, y: -10 },
    delay: 0.15,
  },
  {
    id: 'funny',
    word: 'Funny',
    description: 'There is always a moment where one of us completely loses the plot and starts laughing.',
    size: 'md',
    color: '#E0F2FE',
    glowColor: 'rgba(224, 242, 254, 0.35)',
    defaultPos: { x: -40, y: 15 },
    delay: 0.25,
  },
  {
    id: 'conversations',
    word: 'Conversations',
    description: 'A quick two-minute check-in can somehow turn into an entire hour.',
    size: 'lg',
    color: '#93C5FD',
    glowColor: 'rgba(147, 197, 253, 0.45)',
    defaultPos: { x: 15, y: 12 },
    delay: 0.35,
  },
  {
    id: 'memories',
    word: 'Memories',
    description: "Maybe we haven't known each other forever, but we've already collected quite a few unforgettable ones.",
    size: 'xl',
    color: '#FFFFFF',
    glowColor: 'rgba(255, 255, 255, 0.5)',
    defaultPos: { x: -10, y: 30 },
    delay: 0.18,
  },
  {
    id: 'roadtrips',
    word: 'Road Trips',
    description: 'One single road trip was apparently enough to create an entire legendary chapter.',
    size: 'lg',
    color: '#60A5FA',
    glowColor: 'rgba(96, 165, 250, 0.45)',
    defaultPos: { x: 36, y: 28 },
    delay: 0.28,
  },
  {
    id: 'goodvibes',
    word: 'Good Vibes',
    description: 'Some people just naturally make ordinary moments and mundane days feel better.',
    size: 'md',
    color: '#BAE6FD',
    glowColor: 'rgba(186, 230, 253, 0.4)',
    defaultPos: { x: -32, y: -45 },
    delay: 0.32,
  },
  {
    id: 'friendship',
    word: 'Friendship',
    description: 'Short timeline. Surprisingly genuine story.',
    size: 'xl',
    color: '#FFFFFF',
    glowColor: 'rgba(147, 197, 253, 0.6)',
    defaultPos: { x: 0, y: -40 },
    delay: 0.12,
  },
  {
    id: 'unplanned',
    word: 'Unplanned',
    description: 'Some of the greatest moments we had were the ones that were never planned at all.',
    size: 'md',
    color: '#E0F2FE',
    glowColor: 'rgba(224, 242, 254, 0.35)',
    defaultPos: { x: 38, y: -45 },
    delay: 0.4,
  },
  {
    id: 'genuine',
    word: 'Genuine',
    description: 'Nothing complicated. Just good conversations, honest thoughts, and great company.',
    size: 'lg',
    color: '#93C5FD',
    glowColor: 'rgba(147, 197, 253, 0.45)',
    defaultPos: { x: -38, y: 42 },
    delay: 0.22,
  },
  {
    id: 'somehow',
    word: 'Somehow',
    description: 'Because "somehow" is the only word that explains how naturally this friendship happened.',
    size: 'sm',
    color: '#BAE6FD',
    glowColor: 'rgba(186, 230, 253, 0.35)',
    defaultPos: { x: 20, y: 44 },
    delay: 0.38,
  },
  {
    id: 'coldmilo',
    word: 'Cold Milo ☕',
    description: 'Kosmo Café — just one drink and one outing that became the beginning of our story.',
    size: 'lg',
    color: '#93C5FD',
    glowColor: 'rgba(147, 197, 253, 0.5)',
    defaultPos: { x: -28, y: -48 },
    delay: 0.15,
  },
  {
    id: 'flipdiner',
    word: 'Flip Diner 🍔',
    description: 'That burger, the soups, the endless laughter, and all our mischievous little moments.',
    size: 'lg',
    color: '#BAE6FD',
    glowColor: 'rgba(186, 230, 253, 0.45)',
    defaultPos: { x: 32, y: -46 },
    delay: 0.25,
  },
  {
    id: 'humandiary',
    word: 'Human Diary 📖',
    description: 'Thank you for trusting me with your thoughts, your feelings, and all your little stories.',
    size: 'lg',
    color: '#93C5FD',
    glowColor: 'rgba(147, 197, 253, 0.55)',
    defaultPos: { x: -16, y: 38 },
    delay: 0.28,
  },
  {
    id: 'hersmile',
    word: 'Her Smile ✨',
    description: 'A smile unlike anything I had seen before. So genuine and innocent.',
    size: 'xl',
    color: '#FFFFFF',
    glowColor: 'rgba(255, 255, 255, 0.6)',
    defaultPos: { x: 18, y: -22 },
    delay: 0.18,
  },
  {
    id: 'resilient',
    word: 'Resilient 🌧️',
    description: 'Through misunderstandings, tough phases, and struggles, we kept moving forward together.',
    size: 'md',
    color: '#FFFFFF',
    glowColor: 'rgba(255, 255, 255, 0.45)',
    defaultPos: { x: -36, y: 44 },
    delay: 0.3,
  },
  {
    id: 'us',
    word: 'Us 💙',
    description: 'From that first Cold Milo to Hyderabad — an unforgettable journey.',
    size: 'lg',
    color: '#FFFFFF',
    glowColor: 'rgba(96, 165, 250, 0.65)',
    defaultPos: { x: -2, y: -18 },
    delay: 0.1,
  },
];

export const LITTLE_THINGS_LINES = [
  'COLD MILO AT KOSMO CAFÉ.',
  'BURGER NIGHTS AT FLIP DINER.',
  'THE SOUPS & LATE NIGHT TALKS.',
  'THE MISCHIEVOUS MOMENTS.',
  'FIGHTING THROUGH THE STRUGGLES.',
  'THE HYDERABAD ROAD TRIP.',
  'THE CHAOS & UNFORGETTABLE MEMORIES.',
];

export const STATUS_REPORT = [
  { label: 'Friendship Status', value: 'Still Going Strong 💙', icon: '⏱️' },
  { label: 'Friendship Development Speed', value: 'Questionable 😂', icon: '⚡' },
  { label: 'Number of Random Conversations', value: 'Classified', icon: '🔒' },
  { label: 'Amount of Chaos', value: 'Still Under Investigation', icon: '🔍' },
  { label: 'Overall Vibe', value: '⭐⭐⭐⭐⭐', icon: '✨' },
];
